name: CI

on:
  pull_request:
    branches: [main, develop]
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install
        run: |
          npm ci
          npm i @rollup/rollup-linux-x64-gnu
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          name: packages
          path: |
            ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          name: packages
          path: |
            ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: |
          npm ci
          npm i @rollup/rollup-linux-x64-gnu
      - name: Lint
        run: npm run lint
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          name: packages
          path: |
            ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Unit tests
        run: npm run test:once
